### ISSUE TITLE
[Qt6][Discussion] Porting to Qt6 

### ISSUE THREAD

**Issue by cneben** [cneben/QuickQanava#118]
@walterbrebels

https://github.com/walterbrebels/QuickQanava/commit/09301805252f940d1194418840d7f91061be75a4

**Comment by walterbrebels** [comment]
Are there any issues with the open pull request?

**Comment by cneben** [comment]
No I think it's perfect, but I have no time to review it seriously. Issue has been opened just to have a place to ask you questions about how to keep both Qt5 and Qt6 compatibility.

**Comment by ncnnnnn** [comment]
Qt_6_2_2_MSVC2019_64bit build:
qcmContainer.h(433): error C2039: 'indexOf': is not a member of 'qcm::adapter<C,T>'

**Comment by hzhshok** [comment]
Happened error using QT6.2 as @ncnnnnn said

Errors for master branch:
qcmContainer.h(433): error C2039: 'indexOf': is not a member of 'qcm::adapter<C,T>'
qcmContainer.h(433): error C2039: '.....

After i comments the following line, i showed the other errors: 

//#if QT_VERSION < QT_VERSION_CHECK(6, 0, 0)
template < typename T >
struct adapter< QVector, T > {
...
//#endif

Errors after modified the above lines:
E:\Qt\6.2.1\msvc2019_64\include\QtCore/qmetatype.h(853): error C2027: 使用了未定义类型“qan::Graph”
...

Regards

**Comment by emmenlau** [comment]
Yes, we can confirm this issue.

**Comment by cneben** [comment]
@emmenlau, @ncnnnnn please switch to v2 branch, most samples are now working with Qt 6.2.4 and CMake, this compilation problem is fixed.
